// Generated version information
// This file is auto-generated by sync-version.ts

/**
 * AdCP client library version
 */
export const LIBRARY_VERSION = '2.1.0';

/**
 * AdCP specification version this library is compatible with
 */
export const ADCP_VERSION = '1.6.0';

/**
 * Full version information
 */
export const VERSION_INFO = {
  library: '2.1.0',
  adcp: '1.6.0',
  compatible: true,
  generatedAt: '2025-09-23T15:59:48.569Z'
} as const;

/**
 * Check if this library version is compatible with a given AdCP version
 */
export function isCompatibleWith(adcpVersion: string): boolean {
  // For now, we use exact version matching
  // Future versions might implement semantic version compatibility
  return adcpVersion === ADCP_VERSION;
}
