// Generated version information
// This file is auto-generated by sync-version.ts

/**
 * AdCP SDK library version
 */
export const LIBRARY_VERSION = '6.6.0';

/**
 * AdCP specification version this library is built for
 */
export const ADCP_VERSION = '3.0.5';

/**
 * AdCP major version sent with every request (adcp_major_version field).
 * Sellers validate this against their supported versions and return
 * VERSION_UNSUPPORTED if the version is not in range.
 */
export const ADCP_MAJOR_VERSION = 3;

/**
 * AdCP versions this library maintains backward compatibility with
 */
export const COMPATIBLE_ADCP_VERSIONS = [
  'v2.5',
  'v2.6',
  'v3',
  '3.0.0-beta.1',
  '3.0.0-beta.3',
  '3.0.0',
  '3.0.1',
  '3.0.2',
  '3.0.3',
  '3.0.4',
] as const;

/**
 * String literal union of every AdCP version the SDK formally supports.
 *
 * Used by the per-instance `adcpVersion` constructor option to give callers
 * autocomplete in editors. The intersection with `(string & {})` in the
 * config type preserves the escape hatch — any string is still accepted at
 * the type level — while the literal union surfaces canonical values first.
 */
export type AdcpVersion = (typeof COMPATIBLE_ADCP_VERSIONS)[number];

/**
 * Full version information
 */
export const VERSION_INFO = {
  library: '6.6.0',
  adcp: '3.0.5',
  compatibleVersions: COMPATIBLE_ADCP_VERSIONS,
  generatedAt: '2026-05-02T23:41:28.370Z',
} as const;

/**
 * Get the AdCP specification version this library is built for
 */
export function getAdcpVersion(): string {
  return ADCP_VERSION;
}

/**
 * Get the library version
 */
export function getLibraryVersion(): string {
  return LIBRARY_VERSION;
}

/**
 * Check if this library version is compatible with a given AdCP version
 */
export function isCompatibleWith(adcpVersion: string): boolean {
  return (COMPATIBLE_ADCP_VERSIONS as readonly string[]).includes(adcpVersion);
}

/**
 * Get all AdCP versions this library is compatible with
 */
export function getCompatibleVersions(): readonly string[] {
  return COMPATIBLE_ADCP_VERSIONS;
}

/**
 * Extract the major version number from an AdCP version string.
 *
 * Accepts:
 *   - Semver: '3.0.0', '3.0.1', '3.1.0-beta.1' → 3
 *   - Legacy aliases: 'v3' → 3, 'v2.5' / 'v2.6' → 2
 *
 * Returns NaN for unrecognized strings — callers should validate before passing.
 */
export function parseAdcpMajorVersion(version: string): number {
  const trimmed = version.trim();
  const semverLike = trimmed.startsWith('v') ? trimmed.slice(1) : trimmed;
  const major = parseInt(semverLike.split('.')[0] ?? '', 10);
  return Number.isFinite(major) ? major : NaN;
}
