/**
 * End-to-end coverage for `runAgainstLocalAgent` — the one-call compliance
 * harness sellers use to spin up an in-process agent, seed compliance
 * fixtures, and run storyboards without the 300-line bootstrap.
 *
 * The test uses `capability_discovery`, which only depends on
 * `get_adcp_capabilities` (auto-generated by `createAdcpServer`). If the
 * helper's wiring regresses — misrouted mount path, broken seeding, wrong
 * factory invocation — this storyboard will either skip or fail.
 */

const { test } = require('node:test');
const assert = require('node:assert');
const { runAgainstLocalAgent } = require('../../dist/lib/testing/index.js');
const { createAdcpServer } = require('../../dist/lib/server/index.js');

function makeMinimalAgent() {
  // Register one handler so the auto-generated capabilities response has
  // at least one tool and satisfies AdCP's `supported_protocols` min-items
  // constraint. get_products is the cheapest tool to stand up.
  return createAdcpServer({
    name: 'Helper Test Agent',
    version: '0.0.1',
    mediaBuy: {
      getProducts: async () => ({ products: [] }),
    },
  });
}

test('runs capability_discovery against an in-process agent', async () => {
  const result = await runAgainstLocalAgent({
    createAgent: () => makeMinimalAgent(),
    storyboards: ['capability_discovery'],
    webhookReceiver: false, // not needed for this storyboard; avoids port churn
  });

  assert.strictEqual(result.results.length, 1, 'runs exactly one storyboard');
  const sb = result.results[0];
  assert.strictEqual(sb.storyboard_id, 'capability_discovery');
  assert.ok(sb.overall_passed, `capability_discovery failed: ${JSON.stringify(sb.phases, null, 2)}`);
  assert.ok(result.overall_passed, 'aggregate overall_passed flips when any storyboard fails');
  assert.ok(result.agent_url.endsWith('/mcp'), 'agent_url exposes the canonical mount path');
});

test('resolves capability-driven storyboard set', async () => {
  const result = await runAgainstLocalAgent({
    createAgent: () => makeMinimalAgent(),
    storyboards: {
      // PROTOCOL_TO_PATH uses snake_case internally: `media_buy`, not `media-buy`.
      supported_protocols: ['media_buy'],
      specialisms: ['sales-non-guaranteed'],
    },
    webhookReceiver: false,
    // The media_buy baseline + sales-non-guaranteed bundle is the canonical
    // seller-buys path; we don't assert pass/fail here (handlers are stubs),
    // just that capability resolution plumbed through and ran storyboards.
    bail: true, // stop on first failure so the test doesn't run every sales storyboard
  });

  assert.ok(result.results.length > 0, 'capability resolution produced runnable storyboards');
  const ids = result.results.map(r => r.storyboard_id);
  assert.ok(
    ids.includes('capability_discovery'),
    `expected universal capability_discovery; got: ${ids.join(', ')}`
  );
});

test('throws on unknown storyboard ids', async () => {
  await assert.rejects(
    runAgainstLocalAgent({
      createAgent: () => makeMinimalAgent(),
      storyboards: ['definitely-not-a-real-storyboard'],
    }),
    /unknown storyboard or bundle id/i
  );
});
