// AUTO-GENERATED by scripts/generate-wire-spec-fields.ts. DO NOT EDIT.
// Source: schemas/cache/3.0.6/**/*-request.json
// Generated at: 2026-05-04T08:13:37.396Z

/**
 * Wire-spec field allowlists per request type. The values are exact
 * top-level property names from the AdCP request JSON schemas;
 * `pickWireSpecFields(req, schemaName)` uses them to strip buyer-
 * controlled args to schema-spec fields at the operational fan-out
 * boundary. Drift between this map and the schemas is impossible by
 * construction — both are emitted from the same codegen pass.
 */
export const WIRE_SPEC_FIELDS = {
  /** schemas/cache/3.0.6/brand/acquire-rights-request.json */
  AcquireRightsRequest: ["adcp_major_version","buyer","campaign","context","ext","idempotency_key","pricing_option_id","push_notification_config","revocation_webhook","rights_id"],
  /** schemas/cache/3.0.6/signals/activate-signal-request.json */
  ActivateSignalRequest: ["account","action","adcp_major_version","context","destinations","ext","idempotency_key","pricing_option_id","signal_agent_segment_id"],
  /** schemas/cache/3.0.6/media-buy/build-creative-request.json */
  BuildCreativeRequest: ["account","adcp_major_version","brand","concept_id","context","creative_id","creative_manifest","ext","idempotency_key","include_preview","item_limit","macro_values","media_buy_id","message","package_id","preview_inputs","preview_output_format","preview_quality","quality","target_format_id","target_format_ids"],
  /** schemas/cache/3.0.6/content-standards/calibrate-content-request.json */
  CalibrateContentRequest: ["adcp_major_version","artifact","context","ext","idempotency_key","standards_id"],
  /** schemas/cache/3.0.6/collection/create-collection-list-request.json */
  CreateCollectionListRequest: ["account","adcp_major_version","base_collections","brand","context","description","ext","filters","idempotency_key","name"],
  /** schemas/cache/3.0.6/content-standards/create-content-standards-request.json */
  CreateContentStandardsRequest: ["adcp_major_version","calibration_exemplars","context","ext","idempotency_key","policies","registry_policy_ids","scope"],
  /** schemas/cache/3.0.6/media-buy/create-media-buy-request.json */
  CreateMediaBuyRequest: ["account","adcp_major_version","advertiser_industry","agency_estimate_number","artifact_webhook","brand","context","end_time","ext","idempotency_key","invoice_recipient","io_acceptance","packages","plan_id","po_number","proposal_id","push_notification_config","reporting_webhook","start_time","total_budget"],
  /** schemas/cache/3.0.6/property/create-property-list-request.json */
  CreatePropertyListRequest: ["account","adcp_major_version","base_properties","brand","context","description","ext","filters","idempotency_key","name"],
  /** schemas/cache/3.0.6/collection/delete-collection-list-request.json */
  DeleteCollectionListRequest: ["account","adcp_major_version","context","ext","idempotency_key","list_id"],
  /** schemas/cache/3.0.6/property/delete-property-list-request.json */
  DeletePropertyListRequest: ["account","adcp_major_version","context","ext","idempotency_key","list_id"],
  /** schemas/cache/3.0.6/media-buy/get-media-buy-delivery-request.json */
  GetMediaBuyDeliveryRequest: ["account","adcp_major_version","attribution_window","context","end_date","ext","include_package_daily_breakdown","media_buy_ids","reporting_dimensions","start_date","status_filter"],
  /** schemas/cache/3.0.6/media-buy/log-event-request.json */
  LogEventRequest: ["adcp_major_version","context","event_source_id","events","ext","idempotency_key","test_event_code"],
  /** schemas/cache/3.0.6/media-buy/provide-performance-feedback-request.json */
  ProvidePerformanceFeedbackRequest: ["adcp_major_version","context","creative_id","ext","feedback_source","idempotency_key","measurement_period","media_buy_id","metric_type","package_id","performance_index"],
  /** schemas/cache/3.0.6/governance/report-plan-outcome-request.json */
  ReportPlanOutcomeRequest: ["adcp_major_version","check_id","context","delivery","error","ext","governance_context","idempotency_key","outcome","plan_id","purchase_type","seller_response"],
  /** schemas/cache/3.0.6/account/report-usage-request.json */
  ReportUsageRequest: ["adcp_major_version","context","ext","idempotency_key","reporting_period","usage"],
  /** schemas/cache/3.0.6/sponsored-intelligence/si-initiate-session-request.json */
  SiInitiateSessionRequest: ["adcp_major_version","context","ext","idempotency_key","identity","intent","media_buy_id","offering_id","offering_token","placement","supported_capabilities"],
  /** schemas/cache/3.0.6/sponsored-intelligence/si-send-message-request.json */
  SiSendMessageRequest: ["action_response","adcp_major_version","context","ext","idempotency_key","message","session_id"],
  /** schemas/cache/3.0.6/account/sync-accounts-request.json */
  SyncAccountsRequest: ["accounts","adcp_major_version","context","delete_missing","dry_run","ext","idempotency_key","push_notification_config"],
  /** schemas/cache/3.0.6/media-buy/sync-audiences-request.json */
  SyncAudiencesRequest: ["account","adcp_major_version","audiences","context","delete_missing","ext","idempotency_key"],
  /** schemas/cache/3.0.6/media-buy/sync-catalogs-request.json */
  SyncCatalogsRequest: ["account","adcp_major_version","catalog_ids","catalogs","context","delete_missing","dry_run","ext","idempotency_key","push_notification_config","validation_mode"],
  /** schemas/cache/3.0.6/creative/sync-creatives-request.json */
  SyncCreativesRequest: ["account","adcp_major_version","assignments","context","creative_ids","creatives","delete_missing","dry_run","ext","idempotency_key","push_notification_config","validation_mode"],
  /** schemas/cache/3.0.6/media-buy/sync-event-sources-request.json */
  SyncEventSourcesRequest: ["account","adcp_major_version","context","delete_missing","event_sources","ext","idempotency_key"],
  /** schemas/cache/3.0.6/account/sync-governance-request.json */
  SyncGovernanceRequest: ["accounts","adcp_major_version","context","ext","idempotency_key"],
  /** schemas/cache/3.0.6/governance/sync-plans-request.json */
  SyncPlansRequest: ["adcp_major_version","context","ext","idempotency_key","plans"],
  /** schemas/cache/3.0.6/collection/update-collection-list-request.json */
  UpdateCollectionListRequest: ["account","adcp_major_version","base_collections","brand","context","description","ext","filters","idempotency_key","list_id","name","webhook_url"],
  /** schemas/cache/3.0.6/content-standards/update-content-standards-request.json */
  UpdateContentStandardsRequest: ["adcp_major_version","calibration_exemplars","context","ext","idempotency_key","policies","registry_policy_ids","scope","standards_id"],
  /** schemas/cache/3.0.6/media-buy/update-media-buy-request.json */
  UpdateMediaBuyRequest: ["account","adcp_major_version","canceled","cancellation_reason","context","end_time","ext","idempotency_key","invoice_recipient","media_buy_id","new_packages","packages","paused","push_notification_config","reporting_webhook","revision","start_time"],
  /** schemas/cache/3.0.6/property/update-property-list-request.json */
  UpdatePropertyListRequest: ["account","adcp_major_version","base_properties","brand","context","description","ext","filters","idempotency_key","list_id","name","webhook_url"],
  /** schemas/cache/3.0.6/brand/update-rights-request.json */
  UpdateRightsRequest: ["adcp_major_version","context","end_date","ext","idempotency_key","impression_cap","paused","pricing_option_id","push_notification_config","rights_id"],
} as const;

export type WireSpecRequestName = keyof typeof WIRE_SPEC_FIELDS;
