#!/usr/bin/env tsx
//
// Reads `enumMetadata` off the upstream `media-buy-valid-action.json` schema
// and emits a TypeScript constant the preflight helpers consume.
//
// Run when the schema cache version moves forward (3.1+) or when
// adcontextprotocol/adcp#4480 ships a follow-up that touches the action ->
// field mapping. The output file is checked in so consumers don't pay a
// schema-load cost at runtime.
//
// Usage:
//   npx tsx scripts/generate-media-buy-update-fields.ts
//
// Default source: ADCP_VERSION pinned schema in schemas/cache. Override via
// SCHEMA_PATH env var to point at a candidate upstream copy.

import { readFileSync, writeFileSync, existsSync } from 'fs';
import path from 'path';

interface EnumMetadataEntry {
  update_fields?: string[];
  rollup?: string[];
}

interface ValidActionSchema {
  enum: string[];
  enumMetadata?: Record<string, EnumMetadataEntry>;
  'x-deprecated-enum-values'?: string[];
}

const REPO_ROOT = path.join(__dirname, '..');

function resolveSchemaPath(): string {
  if (process.env.SCHEMA_PATH) return process.env.SCHEMA_PATH;
  const adcpVersion = readFileSync(path.join(REPO_ROOT, 'ADCP_VERSION'), 'utf8').trim();
  const cached = path.join(REPO_ROOT, 'schemas/cache', adcpVersion, 'enums/media-buy-valid-action.json');
  if (!existsSync(cached)) {
    throw new Error(`Schema not found at ${cached}. Run \`npm run sync-schemas\` or set SCHEMA_PATH.`);
  }
  return cached;
}

function main(): void {
  const schemaPath = resolveSchemaPath();
  const schema = JSON.parse(readFileSync(schemaPath, 'utf8')) as ValidActionSchema;
  const meta = schema.enumMetadata ?? {};
  const deprecated = new Set(schema['x-deprecated-enum-values'] ?? []);

  if (Object.keys(meta).length === 0) {
    throw new Error(
      `Schema at ${schemaPath} has no enumMetadata block - likely a pre-3.1 cache. ` +
        `Bump the schema cache before regenerating.`
    );
  }

  const rows = schema.enum.map(action => {
    const entry = meta[action] ?? {};
    return {
      action,
      update_fields: entry.update_fields ?? [],
      rollup: entry.rollup ?? null,
      deprecated: deprecated.has(action),
    };
  });

  const banner =
    '// Generated by scripts/generate-media-buy-update-fields.ts.\n' +
    '// Source: schemas/cache/<adcp_version>/enums/media-buy-valid-action.json (enumMetadata).\n' +
    '// Do not hand-edit - regenerate after a schema bump.\n\n';

  const tsImports = "import type { MediaBuyValidAction } from './types';\n\n";

  const tsEntry =
    'export interface UpdateFieldEntry {\n' +
    '  /** Dotted paths into the update_media_buy request body this action covers. */\n' +
    '  readonly update_fields: readonly string[];\n' +
    '  /** Fine-grained values this action rolls up to (legacy coarse actions only). */\n' +
    '  readonly rollup: readonly MediaBuyValidAction[] | null;\n' +
    '  /** True for `x-deprecated-enum-values` (legacy coarse vocabulary). */\n' +
    '  readonly deprecated: boolean;\n' +
    '}\n\n';

  const tableLines = rows
    .map(row => {
      const fields = row.update_fields.map(f => JSON.stringify(f)).join(', ');
      const rollup = row.rollup === null ? 'null' : `[${row.rollup.map(r => JSON.stringify(r)).join(', ')}] as const`;
      return (
        `  ${JSON.stringify(row.action)}: {\n` +
        `    update_fields: [${fields}] as const,\n` +
        `    rollup: ${rollup},\n` +
        `    deprecated: ${row.deprecated},\n` +
        `  },`
      );
    })
    .join('\n');

  const tableConst =
    'export const UPDATE_FIELDS_BY_ACTION: Readonly<\n' +
    '  Record<MediaBuyValidAction, UpdateFieldEntry>\n' +
    '> = {\n' +
    tableLines +
    '\n} as const;\n\n';

  // Inverse index: dotted path -> actions that touch it. Used by the
  // resolver to map a request diff back to actions.
  const inverse: Record<string, string[]> = {};
  for (const row of rows) {
    if (row.deprecated) continue;
    for (const field of row.update_fields) {
      if (!inverse[field]) inverse[field] = [];
      inverse[field].push(row.action);
    }
  }
  const inverseLines = Object.entries(inverse)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(
      ([field, actions]) => `  ${JSON.stringify(field)}: [${actions.map(a => JSON.stringify(a)).join(', ')}] as const,`
    )
    .join('\n');

  const inverseConst =
    'export const ACTIONS_BY_FIELD: Readonly<\n' +
    '  Record<string, readonly MediaBuyValidAction[]>\n' +
    '> = {\n' +
    inverseLines +
    '\n} as const;\n\n';

  const legacyExport =
    "export { LEGACY_COARSE_ACTIONS } from './types';\n" + "export type { LegacyCoarseAction } from './types';\n";

  const output = banner + tsImports + tsEntry + tableConst + inverseConst + legacyExport;
  const outPath = path.join(REPO_ROOT, 'src/lib/media-buy/update-fields.generated.ts');
  writeFileSync(outPath, output, 'utf8');
  process.stdout.write(`Wrote ${outPath}\n`);
}

main();
