# GitHub Pages Configuration
title: ADCP Client Documentation
description: Official documentation for the @adcp/client TypeScript/JavaScript library
theme: jekyll-theme-cayman

# Navigation
nav:
  - title: Home
    url: /
  - title: Getting Started
    url: /getting-started
  - title: API Reference
    url: /api/
  - title: Guides
    url: /guides/ASYNC-DOCUMENTATION-INDEX
  - title: GitHub
    url: https://github.com/your-org/adcp-client

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - tsconfig.json