// Generated Zod v4 schemas from TypeScript types
// Generated at: 2025-12-19T12:50:36.265Z
// Sources:
//   - core.generated.ts (core types)
//   - tools.generated.ts (tool types)
//
// These schemas provide runtime validation for AdCP data structures
// Generated using ts-to-zod from TypeScript type definitions

// Generated by ts-to-zod
import { z } from "zod";

export const MediaBuyStatusSchema = z.union([z.literal("pending_activation"), z.literal("active"), z.literal("paused"), z.literal("completed")]);

export const PacingSchema = z.union([z.literal("even"), z.literal("asap"), z.literal("front_loaded")]);

export const ExtensionObjectSchema = z.record(z.string(), z.unknown());

export const CreativeAssignmentSchema = z.object({
    creative_id: z.string(),
    weight: z.number().nullish(),
    placement_ids: z.tuple([z.string()]).rest(z.string()).nullish()
});

export const FormatIDSchema = z.object({
    agent_url: z.string(),
    id: z.string(),
    width: z.number().nullish(),
    height: z.number().nullish(),
    duration_ms: z.number().nullish()
});

export const FrequencyCapSchema = z.object({
    suppress_minutes: z.number()
});

export const VASTVersionSchema = z.union([z.literal("2.0"), z.literal("3.0"), z.literal("4.0"), z.literal("4.1"), z.literal("4.2")]);

export const VASTTrackingEventSchema = z.union([z.literal("start"), z.literal("firstQuartile"), z.literal("midpoint"), z.literal("thirdQuartile"), z.literal("complete"), z.literal("impression"), z.literal("click"), z.literal("pause"), z.literal("resume"), z.literal("skip"), z.literal("mute"), z.literal("unmute"), z.literal("fullscreen"), z.literal("exitFullscreen"), z.literal("playerExpand"), z.literal("playerCollapse")]);

export const VASTVersion1Schema = z.union([z.literal("2.0"), z.literal("3.0"), z.literal("4.0"), z.literal("4.1"), z.literal("4.2")]);

export const DAASTVersionSchema = z.union([z.literal("1.0"), z.literal("1.1")]);

export const DAASTTrackingEventSchema = z.union([z.literal("start"), z.literal("firstQuartile"), z.literal("midpoint"), z.literal("thirdQuartile"), z.literal("complete"), z.literal("impression"), z.literal("pause"), z.literal("resume"), z.literal("skip"), z.literal("mute"), z.literal("unmute")]);

export const DAASTVersion1Schema = z.union([z.literal("1.0"), z.literal("1.1")]);

export const ImageAssetSchema = z.object({
    url: z.string(),
    width: z.number(),
    height: z.number(),
    format: z.string().nullish(),
    alt_text: z.string().nullish()
});

export const VideoAssetSchema = z.object({
    url: z.string(),
    width: z.number(),
    height: z.number(),
    duration_ms: z.number().nullish(),
    format: z.string().nullish(),
    bitrate_kbps: z.number().nullish()
});

export const AudioAssetSchema = z.object({
    url: z.string(),
    duration_ms: z.number().nullish(),
    format: z.string().nullish(),
    bitrate_kbps: z.number().nullish()
});

export const TextAssetSchema = z.object({
    content: z.string(),
    language: z.string().nullish()
});

export const HTMLAssetSchema = z.object({
    content: z.string(),
    version: z.string().nullish()
});

export const CSSAssetSchema = z.object({
    content: z.string(),
    media: z.string().nullish()
});

export const VASTAssetSchema = z.union([z.object({
        delivery_type: z.literal("url"),
        url: z.string(),
        vast_version: VASTVersionSchema.nullish(),
        vpaid_enabled: z.boolean().nullish(),
        duration_ms: z.number().nullish(),
        tracking_events: z.array(VASTTrackingEventSchema).nullish()
    }), z.object({
        delivery_type: z.literal("inline"),
        content: z.string(),
        vast_version: VASTVersion1Schema.nullish(),
        vpaid_enabled: z.boolean().nullish(),
        duration_ms: z.number().nullish(),
        tracking_events: z.array(VASTTrackingEventSchema).nullish()
    })]);

export const DAASTAssetSchema = z.union([z.object({
        delivery_type: z.literal("url"),
        url: z.string(),
        daast_version: DAASTVersionSchema.nullish(),
        duration_ms: z.number().nullish(),
        tracking_events: z.array(DAASTTrackingEventSchema).nullish(),
        companion_ads: z.boolean().nullish()
    }), z.object({
        delivery_type: z.literal("inline"),
        content: z.string(),
        daast_version: DAASTVersion1Schema.nullish(),
        duration_ms: z.number().nullish(),
        tracking_events: z.array(DAASTTrackingEventSchema).nullish(),
        companion_ads: z.boolean().nullish()
    })]);

export const JavaScriptModuleTypeSchema = z.union([z.literal("esm"), z.literal("commonjs"), z.literal("script")]);

export const PromotedProductsSchema = z.object({
    manifest_skus: z.array(z.string()).nullish(),
    manifest_tags: z.array(z.string()).nullish(),
    manifest_category: z.string().nullish(),
    manifest_query: z.string().nullish()
});

export const AssetContentTypeSchema = z.union([z.literal("image"), z.literal("video"), z.literal("audio"), z.literal("text"), z.literal("markdown"), z.literal("html"), z.literal("css"), z.literal("javascript"), z.literal("vast"), z.literal("daast"), z.literal("promoted_offerings"), z.literal("url"), z.literal("webhook")]);

export const URLAssetTypeSchema = z.union([z.literal("clickthrough"), z.literal("tracker_pixel"), z.literal("tracker_script")]);

export const DeliveryTypeSchema = z.union([z.literal("guaranteed"), z.literal("non_guaranteed")]);

export const CPMFixedRatePricingOptionSchema = z.object({
    pricing_option_id: z.string(),
    pricing_model: z.literal("cpm"),
    rate: z.number(),
    currency: z.string(),
    is_fixed: z.literal(true),
    min_spend_per_package: z.number().nullish()
});

export const CPMAuctionPricingOptionSchema = z.object({
    pricing_option_id: z.string(),
    pricing_model: z.literal("cpm"),
    currency: z.string(),
    is_fixed: z.literal(false),
    price_guidance: z.object({
        floor: z.number(),
        p25: z.number().nullish(),
        p50: z.number().nullish(),
        p75: z.number().nullish(),
        p90: z.number().nullish()
    }),
    min_spend_per_package: z.number().nullish()
});

export const VCPMFixedRatePricingOptionSchema = z.object({
    pricing_option_id: z.string(),
    pricing_model: z.literal("vcpm"),
    rate: z.number(),
    currency: z.string(),
    is_fixed: z.literal(true),
    min_spend_per_package: z.number().nullish()
});

export const VCPMAuctionPricingOptionSchema = z.object({
    pricing_option_id: z.string(),
    pricing_model: z.literal("vcpm"),
    currency: z.string(),
    is_fixed: z.literal(false),
    price_guidance: z.object({
        floor: z.number(),
        p25: z.number().nullish(),
        p50: z.number().nullish(),
        p75: z.number().nullish(),
        p90: z.number().nullish()
    }),
    min_spend_per_package: z.number().nullish()
});

export const CPCPricingOptionSchema = z.object({
    pricing_option_id: z.string(),
    pricing_model: z.literal("cpc"),
    rate: z.number(),
    currency: z.string(),
    is_fixed: z.literal(true),
    min_spend_per_package: z.number().nullish()
});

export const CPCVPricingOptionSchema = z.object({
    pricing_option_id: z.string(),
    pricing_model: z.literal("cpcv"),
    rate: z.number(),
    currency: z.string(),
    is_fixed: z.literal(true),
    min_spend_per_package: z.number().nullish()
});

export const CPVPricingOptionSchema = z.object({
    pricing_option_id: z.string(),
    pricing_model: z.literal("cpv"),
    rate: z.number(),
    currency: z.string(),
    is_fixed: z.literal(true),
    parameters: z.object({
        view_threshold: z.union([z.number(), z.object({
                duration_seconds: z.number()
            })])
    }),
    min_spend_per_package: z.number().nullish()
});

export const CPPPricingOptionSchema = z.object({
    pricing_option_id: z.string(),
    pricing_model: z.literal("cpp"),
    rate: z.number(),
    currency: z.string(),
    is_fixed: z.literal(true),
    parameters: z.object({
        demographic: z.string(),
        min_points: z.number().nullish()
    }),
    min_spend_per_package: z.number().nullish()
});

export const FlatRatePricingOptionSchema = z.object({
    pricing_option_id: z.string(),
    pricing_model: z.literal("flat_rate"),
    rate: z.number(),
    currency: z.string(),
    is_fixed: z.literal(true),
    parameters: z.object({
        duration_hours: z.number().nullish(),
        sov_percentage: z.number().nullish(),
        loop_duration_seconds: z.number().nullish(),
        min_plays_per_hour: z.number().nullish(),
        venue_package: z.string().nullish(),
        estimated_impressions: z.number().nullish(),
        daypart: z.string().nullish()
    }).nullish(),
    min_spend_per_package: z.number().nullish()
});

export const PlacementSchema = z.object({
    placement_id: z.string(),
    name: z.string(),
    description: z.string().nullish(),
    format_ids: z.tuple([FormatIDSchema]).rest(FormatIDSchema).nullish()
});

export const PricingOptionSchema = z.union([CPMFixedRatePricingOptionSchema, CPMAuctionPricingOptionSchema, VCPMFixedRatePricingOptionSchema, VCPMAuctionPricingOptionSchema, CPCPricingOptionSchema, CPCVPricingOptionSchema, CPVPricingOptionSchema, CPPPricingOptionSchema, FlatRatePricingOptionSchema]);

export const MeasurementSchema = z.object({
    type: z.string(),
    attribution: z.string(),
    window: z.string().nullish(),
    reporting: z.string()
});

export const FormatID1Schema = z.object({
    agent_url: z.string(),
    id: z.string(),
    width: z.number().nullish(),
    height: z.number().nullish(),
    duration_ms: z.number().nullish()
});

export const FormatID2Schema = z.object({
    agent_url: z.string(),
    id: z.string(),
    width: z.number().nullish(),
    height: z.number().nullish(),
    duration_ms: z.number().nullish()
});

export const ReportingFrequencySchema = z.union([z.literal("hourly"), z.literal("daily"), z.literal("monthly")]);

export const AvailableMetricSchema = z.union([z.literal("impressions"), z.literal("spend"), z.literal("clicks"), z.literal("ctr"), z.literal("video_completions"), z.literal("completion_rate"), z.literal("conversions"), z.literal("viewability"), z.literal("engagement_rate")]);

export const CoBrandingRequirementSchema = z.union([z.literal("required"), z.literal("optional"), z.literal("none")]);

export const LandingPageRequirementSchema = z.union([z.literal("any"), z.literal("retailer_site_only"), z.literal("must_include_retailer")]);

export const PropertyIdentifierTypesSchema = z.union([z.literal("domain"), z.literal("subdomain"), z.literal("network_id"), z.literal("ios_bundle"), z.literal("android_package"), z.literal("apple_app_store_id"), z.literal("google_play_id"), z.literal("roku_store_id"), z.literal("fire_tv_asin"), z.literal("samsung_app_id"), z.literal("apple_tv_bundle"), z.literal("bundle_id"), z.literal("venue_id"), z.literal("screen_id"), z.literal("openooh_venue_type"), z.literal("rss_url"), z.literal("apple_podcast_id"), z.literal("spotify_show_id"), z.literal("podcast_guid")]);

export const PropertyIDSchema = z.string();

export const PropertyTypeSchema = z.union([z.literal("website"), z.literal("mobile_app"), z.literal("ctv_app"), z.literal("dooh"), z.literal("podcast"), z.literal("radio"), z.literal("streaming_audio")]);

export const PropertyTagSchema = z.string();

export const ErrorSchema = z.object({
    code: z.string(),
    message: z.string(),
    field: z.string().nullish(),
    suggestion: z.string().nullish(),
    retry_after: z.number().nullish(),
    details: z.record(z.string(), z.unknown()).nullish()
});

export const ContextObjectSchema = z.record(z.string(), z.unknown());

export const BrandManifestSchema = z.object({
    url: z.string().nullish(),
    name: z.string(),
    logos: z.array(z.object({
        url: z.string(),
        tags: z.array(z.string()).nullish(),
        width: z.number().nullish(),
        height: z.number().nullish()
    })).nullish(),
    colors: z.object({
        primary: z.string().nullish(),
        secondary: z.string().nullish(),
        accent: z.string().nullish(),
        background: z.string().nullish(),
        text: z.string().nullish()
    }).nullish(),
    fonts: z.object({
        primary: z.string().nullish(),
        secondary: z.string().nullish(),
        font_urls: z.array(z.string()).nullish()
    }).nullish(),
    tone: z.string().nullish(),
    tagline: z.string().nullish(),
    assets: z.array(z.object({
        asset_id: z.string(),
        asset_type: AssetContentTypeSchema,
        url: z.string(),
        tags: z.array(z.string()).nullish(),
        name: z.string().nullish(),
        description: z.string().nullish(),
        width: z.number().nullish(),
        height: z.number().nullish(),
        duration_seconds: z.number().nullish(),
        file_size_bytes: z.number().nullish(),
        format: z.string().nullish(),
        metadata: z.record(z.string(), z.unknown()).nullish()
    })).nullish(),
    product_catalog: z.object({
        feed_url: z.string(),
        feed_format: z.union([z.literal("google_merchant_center"), z.literal("facebook_catalog"), z.literal("custom")]).nullish(),
        categories: z.array(z.string()).nullish(),
        last_updated: z.string().nullish(),
        update_frequency: z.union([z.literal("realtime"), z.literal("hourly"), z.literal("daily"), z.literal("weekly")]).nullish()
    }).nullish(),
    disclaimers: z.array(z.object({
        text: z.string(),
        context: z.string().nullish(),
        required: z.boolean().nullish()
    })).nullish(),
    industry: z.string().nullish(),
    target_audience: z.string().nullish(),
    contact: z.object({
        email: z.string().nullish(),
        phone: z.string().nullish()
    }).nullish(),
    metadata: z.object({
        created_date: z.string().nullish(),
        updated_date: z.string().nullish(),
        version: z.string().nullish()
    }).nullish()
});

export const BrandManifestReferenceSchema = z.union([BrandManifestSchema, z.string()]);

export const PublisherPropertySelectorSchema = z.union([z.object({
        publisher_domain: z.string(),
        selection_type: z.literal("all")
    }), z.object({
        publisher_domain: z.string(),
        selection_type: z.literal("by_id"),
        property_ids: z.tuple([PropertyIDSchema]).rest(PropertyIDSchema)
    }), z.object({
        publisher_domain: z.string(),
        selection_type: z.literal("by_tag"),
        property_tags: z.tuple([PropertyTagSchema]).rest(PropertyTagSchema)
    })]);

export const ReportingCapabilitiesSchema = z.object({
    available_reporting_frequencies: z.tuple([ReportingFrequencySchema]).rest(ReportingFrequencySchema),
    expected_delay_minutes: z.number(),
    timezone: z.string(),
    supports_webhooks: z.boolean(),
    available_metrics: z.array(AvailableMetricSchema)
});

export const CreativePolicySchema = z.object({
    co_branding: CoBrandingRequirementSchema,
    landing_page: LandingPageRequirementSchema,
    templates_available: z.boolean()
});

export const FormatCategorySchema = z.union([z.literal("audio"), z.literal("video"), z.literal("display"), z.literal("native"), z.literal("dooh"), z.literal("rich_media"), z.literal("universal")]);

export const CreativeAgentCapabilitySchema = z.union([z.literal("validation"), z.literal("assembly"), z.literal("generation"), z.literal("preview")]);

export const FormatIDParameterSchema = z.union([z.literal("dimensions"), z.literal("duration")]);

export const AssetContentType1Schema = z.union([z.literal("image"), z.literal("video"), z.literal("audio"), z.literal("text"), z.literal("markdown"), z.literal("html"), z.literal("css"), z.literal("javascript"), z.literal("vast"), z.literal("daast"), z.literal("promoted_offerings"), z.literal("url"), z.literal("webhook")]);

export const FormatID3Schema = z.object({
    agent_url: z.string(),
    id: z.string(),
    width: z.number().nullish(),
    height: z.number().nullish(),
    duration_ms: z.number().nullish()
});

export const BrandManifestReference1Schema = z.union([BrandManifestSchema, z.string()]);

export const StartTimingSchema = z.union([z.literal("asap"), z.string()]);

export const TargetingOverlaySchema = z.object({
    geo_country_any_of: z.array(z.string()).nullish(),
    geo_region_any_of: z.array(z.string()).nullish(),
    geo_metro_any_of: z.array(z.string()).nullish(),
    geo_postal_code_any_of: z.array(z.string()).nullish(),
    axe_include_segment: z.string().nullish(),
    axe_exclude_segment: z.string().nullish(),
    frequency_cap: FrequencyCapSchema.nullish()
});

export const JavaScriptAssetSchema = z.object({
    content: z.string(),
    module_type: JavaScriptModuleTypeSchema.nullish()
});

export const PromotedOfferingsSchema = z.object({
    brand_manifest: BrandManifestReferenceSchema,
    product_selectors: PromotedProductsSchema.nullish(),
    offerings: z.array(z.object({
        name: z.string(),
        description: z.string().nullish(),
        assets: z.array(z.record(z.string(), z.unknown())).nullish()
    })).nullish(),
    asset_selectors: z.object({
        tags: z.array(z.string()).nullish(),
        asset_types: z.array(z.union([z.literal("image"), z.literal("video"), z.literal("audio"), z.literal("vast"), z.literal("daast"), z.literal("text"), z.literal("url"), z.literal("html"), z.literal("css"), z.literal("javascript"), z.literal("webhook")])).nullish(),
        exclude_tags: z.array(z.string()).nullish()
    }).nullish()
});

export const URLAssetSchema = z.object({
    url: z.string(),
    url_type: URLAssetTypeSchema.nullish(),
    description: z.string().nullish()
});

export const AuthenticationSchemeSchema = z.union([z.literal("Bearer"), z.literal("HMAC-SHA256")]);

export const CreateMediaBuyErrorSchema = z.object({
    errors: z.tuple([ErrorSchema]).rest(ErrorSchema),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const PackageSchema = z.object({
    package_id: z.string(),
    buyer_ref: z.string().nullish(),
    product_id: z.string().nullish(),
    budget: z.number().nullish(),
    pacing: PacingSchema.nullish(),
    pricing_option_id: z.string().nullish(),
    bid_price: z.number().nullish(),
    impressions: z.number().nullish(),
    targeting_overlay: TargetingOverlaySchema.nullish(),
    creative_assignments: z.array(CreativeAssignmentSchema).nullish(),
    format_ids_to_provide: z.array(FormatIDSchema).nullish(),
    paused: z.boolean().nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const CreativeAssetSchema = z.object({
    creative_id: z.string(),
    name: z.string(),
    format_id: FormatID1Schema,
    assets: z.record(z.string(), z.union([ImageAssetSchema, VideoAssetSchema, AudioAssetSchema, TextAssetSchema, HTMLAssetSchema, CSSAssetSchema, JavaScriptAssetSchema, VASTAssetSchema, DAASTAssetSchema, PromotedOfferingsSchema, URLAssetSchema])),
    inputs: z.array(z.object({
        name: z.string(),
        macros: z.record(z.string(), z.string()).nullish(),
        context_description: z.string().nullish()
    })).nullish(),
    tags: z.array(z.string()).nullish(),
    approved: z.boolean().nullish(),
    weight: z.number().nullish(),
    placement_ids: z.tuple([z.string()]).rest(z.string()).nullish()
});

export const ValidationModeSchema = z.union([z.literal("strict"), z.literal("lenient")]);

export const PushNotificationConfigSchema = z.object({
    url: z.string(),
    token: z.string().nullish(),
    authentication: z.object({
        schemes: z.tuple([AuthenticationSchemeSchema]),
        credentials: z.string()
    })
});

export const SyncCreativesErrorSchema = z.object({
    errors: z.tuple([ErrorSchema]).rest(ErrorSchema),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const CreativeSortFieldSchema = z.union([z.literal("created_date"), z.literal("updated_date"), z.literal("name"), z.literal("status"), z.literal("assignment_count"), z.literal("performance_score")]);

export const SortDirectionSchema = z.union([z.literal("asc"), z.literal("desc")]);

export const CreativeStatusSchema = z.union([z.literal("processing"), z.literal("approved"), z.literal("rejected"), z.literal("pending_review")]);

export const CreativeStatus1Schema = z.union([z.literal("processing"), z.literal("approved"), z.literal("rejected"), z.literal("pending_review")]);

export const SubAssetSchema = z.union([z.object({
        asset_kind: z.literal("media"),
        asset_type: z.string(),
        asset_id: z.string(),
        content_uri: z.string()
    }), z.object({
        asset_kind: z.literal("text"),
        asset_type: z.string(),
        asset_id: z.string(),
        content: z.union([z.string(), z.array(z.string())])
    })]);

export const ListCreativesResponseSchema = z.object({
    query_summary: z.object({
        total_matching: z.number(),
        returned: z.number(),
        filters_applied: z.array(z.string()).nullish(),
        sort_applied: z.object({
            field: z.string().nullish(),
            direction: SortDirectionSchema.nullish()
        }).nullish()
    }),
    pagination: z.object({
        limit: z.number(),
        offset: z.number(),
        has_more: z.boolean(),
        total_pages: z.number().nullish(),
        current_page: z.number().nullish()
    }),
    creatives: z.array(z.object({
        creative_id: z.string(),
        name: z.string(),
        format_id: FormatIDSchema,
        status: CreativeStatusSchema,
        created_date: z.string(),
        updated_date: z.string(),
        assets: z.record(z.string(), z.union([ImageAssetSchema, VideoAssetSchema, AudioAssetSchema, TextAssetSchema, HTMLAssetSchema, CSSAssetSchema, JavaScriptAssetSchema, VASTAssetSchema, DAASTAssetSchema, PromotedOfferingsSchema, URLAssetSchema])).nullish(),
        tags: z.array(z.string()).nullish(),
        assignments: z.object({
            assignment_count: z.number(),
            assigned_packages: z.array(z.object({
                package_id: z.string(),
                package_name: z.string().nullish(),
                assigned_date: z.string(),
                status: z.union([z.literal("active"), z.literal("paused"), z.literal("ended")])
            })).nullish()
        }).nullish(),
        performance: z.object({
            impressions: z.number().nullish(),
            clicks: z.number().nullish(),
            ctr: z.number().nullish(),
            conversion_rate: z.number().nullish(),
            performance_score: z.number().nullish(),
            last_updated: z.string()
        }).nullish(),
        sub_assets: z.array(SubAssetSchema).nullish()
    })),
    format_summary: z.record(z.string(), z.number()).nullish(),
    status_summary: z.object({
        approved: z.number().nullish(),
        pending_review: z.number().nullish(),
        rejected: z.number().nullish(),
        archived: z.number().nullish()
    }).nullish(),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const UpdateMediaBuyRequest1Schema = z.object({
    media_buy_id: z.string().nullish(),
    buyer_ref: z.string().nullish(),
    paused: z.boolean().nullish(),
    start_time: StartTimingSchema.nullish(),
    end_time: z.string().nullish(),
    packages: z.array(z.union([z.record(z.string(), z.unknown()), z.record(z.string(), z.unknown())])).nullish(),
    push_notification_config: PushNotificationConfigSchema.nullish(),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const UpdateMediaBuySuccessSchema = z.object({
    media_buy_id: z.string(),
    buyer_ref: z.string(),
    implementation_date: z.string().nullish().nullable(),
    affected_packages: z.array(PackageSchema).nullish(),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const UpdateMediaBuyErrorSchema = z.object({
    errors: z.tuple([ErrorSchema]).rest(ErrorSchema),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const GetMediaBuyDeliveryRequestSchema = z.object({
    media_buy_ids: z.array(z.string()).nullish(),
    buyer_refs: z.array(z.string()).nullish(),
    status_filter: z.union([MediaBuyStatusSchema, z.array(MediaBuyStatusSchema)]).nullish(),
    start_date: z.string().nullish(),
    end_date: z.string().nullish(),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const PricingModelSchema = z.union([z.literal("cpm"), z.literal("vcpm"), z.literal("cpc"), z.literal("cpcv"), z.literal("cpv"), z.literal("cpp"), z.literal("flat_rate")]);

export const DeliveryMetricsSchema = z.record(z.string(), z.unknown()).and(z.object({
    impressions: z.number().nullish(),
    spend: z.number().nullish(),
    clicks: z.number().nullish(),
    ctr: z.number().nullish(),
    views: z.number().nullish(),
    completed_views: z.number().nullish(),
    completion_rate: z.number().nullish(),
    conversions: z.number().nullish(),
    leads: z.number().nullish(),
    grps: z.number().nullish(),
    reach: z.number().nullish(),
    frequency: z.number().nullish(),
    quartile_data: z.object({
        q1_views: z.number().nullish(),
        q2_views: z.number().nullish(),
        q3_views: z.number().nullish(),
        q4_views: z.number().nullish()
    }).nullish(),
    dooh_metrics: z.object({
        loop_plays: z.number().nullish(),
        screens_used: z.number().nullish(),
        screen_time_seconds: z.number().nullish(),
        sov_achieved: z.number().nullish(),
        calculation_notes: z.string().nullish(),
        venue_breakdown: z.array(z.object({
            venue_id: z.string(),
            venue_name: z.string().nullish(),
            venue_type: z.string().nullish(),
            impressions: z.number(),
            loop_plays: z.number().nullish(),
            screens_used: z.number().nullish()
        })).nullish()
    }).nullish()
}));

export const PricingModel1Schema = z.union([z.literal("cpm"), z.literal("vcpm"), z.literal("cpc"), z.literal("cpcv"), z.literal("cpv"), z.literal("cpp"), z.literal("flat_rate")]);

export const ListAuthorizedPropertiesRequestSchema = z.object({
    publisher_domains: z.tuple([z.string()]).rest(z.string()).nullish(),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const AdvertisingChannelsSchema = z.union([z.literal("display"), z.literal("video"), z.literal("audio"), z.literal("native"), z.literal("dooh"), z.literal("ctv"), z.literal("podcast"), z.literal("retail"), z.literal("social")]);

export const MetricTypeSchema = z.union([z.literal("overall_performance"), z.literal("conversion_rate"), z.literal("brand_lift"), z.literal("click_through_rate"), z.literal("completion_rate"), z.literal("viewability"), z.literal("brand_safety"), z.literal("cost_efficiency")]);

export const FeedbackSourceSchema = z.union([z.literal("buyer_attribution"), z.literal("third_party_measurement"), z.literal("platform_analytics"), z.literal("verification_partner")]);

export const ProvidePerformanceFeedbackRequest1Schema = z.object({
    media_buy_id: z.string().nullish(),
    buyer_ref: z.string().nullish(),
    measurement_period: z.object({
        start: z.string(),
        end: z.string()
    }).nullish(),
    performance_index: z.number().nullish(),
    package_id: z.string().nullish(),
    creative_id: z.string().nullish(),
    metric_type: MetricTypeSchema.nullish(),
    feedback_source: FeedbackSourceSchema.nullish(),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const ProvidePerformanceFeedbackSuccessSchema = z.object({
    success: z.literal(true),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const ProvidePerformanceFeedbackErrorSchema = z.object({
    errors: z.tuple([ErrorSchema]).rest(ErrorSchema),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const HTTPMethodSchema = z.union([z.literal("GET"), z.literal("POST")]);

export const WebhookResponseTypeSchema = z.union([z.literal("html"), z.literal("json"), z.literal("xml"), z.literal("javascript")]);

export const WebhookSecurityMethodSchema = z.union([z.literal("hmac_sha256"), z.literal("api_key"), z.literal("none")]);

export const BuildCreativeErrorSchema = z.object({
    errors: z.tuple([ErrorSchema]).rest(ErrorSchema),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const PreviewOutputFormatSchema = z.union([z.literal("url"), z.literal("html")]);

export const PreviewOutputFormat1Schema = z.union([z.literal("url"), z.literal("html")]);

export const PreviewOutputFormat2Schema = z.union([z.literal("url"), z.literal("html")]);

export const DestinationSchema = z.union([z.object({
        type: z.literal("platform"),
        platform: z.string(),
        account: z.string().nullish()
    }), z.object({
        type: z.literal("agent"),
        agent_url: z.string(),
        account: z.string().nullish()
    })]);

export const ActivationKeySchema = z.union([z.object({
        type: z.literal("segment_id"),
        segment_id: z.string()
    }), z.object({
        type: z.literal("key_value"),
        key: z.string(),
        value: z.string()
    })]);

export const ActivationKey1Schema = z.union([z.object({
        type: z.literal("segment_id"),
        segment_id: z.string()
    }), z.object({
        type: z.literal("key_value"),
        key: z.string(),
        value: z.string()
    })]);

export const SignalCatalogTypeSchema = z.union([z.literal("marketplace"), z.literal("custom"), z.literal("owned")]);

export const DeploymentSchema = z.union([z.object({
        type: z.literal("platform"),
        platform: z.string(),
        account: z.string().nullish(),
        is_live: z.boolean(),
        activation_key: ActivationKeySchema.nullish(),
        estimated_activation_duration_minutes: z.number().nullish(),
        deployed_at: z.string().nullish()
    }), z.object({
        type: z.literal("agent"),
        agent_url: z.string(),
        account: z.string().nullish(),
        is_live: z.boolean(),
        activation_key: ActivationKey1Schema.nullish(),
        estimated_activation_duration_minutes: z.number().nullish(),
        deployed_at: z.string().nullish()
    })]);

export const ActivateSignalRequestSchema = z.object({
    signal_agent_segment_id: z.string(),
    deployments: z.tuple([DestinationSchema]).rest(DestinationSchema),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const ActivateSignalSuccessSchema = z.object({
    deployments: z.array(DeploymentSchema),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const ActivateSignalErrorSchema = z.object({
    errors: z.tuple([ErrorSchema]).rest(ErrorSchema),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const MediaBuySchema = z.object({
    media_buy_id: z.string(),
    buyer_ref: z.string().nullish(),
    status: MediaBuyStatusSchema,
    promoted_offering: z.string(),
    total_budget: z.number(),
    packages: z.array(PackageSchema),
    creative_deadline: z.string().nullish(),
    created_at: z.string().nullish(),
    updated_at: z.string().nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const ProductSchema = z.object({
    product_id: z.string(),
    name: z.string(),
    description: z.string(),
    publisher_properties: z.tuple([PublisherPropertySelectorSchema]).rest(PublisherPropertySelectorSchema),
    format_ids: z.array(FormatIDSchema),
    placements: z.tuple([PlacementSchema]).rest(PlacementSchema).nullish(),
    delivery_type: DeliveryTypeSchema,
    pricing_options: z.tuple([PricingOptionSchema]).rest(PricingOptionSchema),
    estimated_exposures: z.number().nullish(),
    measurement: MeasurementSchema.nullish(),
    delivery_measurement: z.object({
        provider: z.string(),
        notes: z.string().nullish()
    }),
    reporting_capabilities: ReportingCapabilitiesSchema.nullish(),
    creative_policy: CreativePolicySchema.nullish(),
    is_custom: z.boolean().nullish(),
    brief_relevance: z.string().nullish(),
    expires_at: z.string().nullish(),
    product_card: z.object({
        format_id: FormatID1Schema,
        manifest: z.record(z.string(), z.unknown())
    }).nullish(),
    product_card_detailed: z.object({
        format_id: FormatID2Schema,
        manifest: z.record(z.string(), z.unknown())
    }).nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const PropertySchema = z.object({
    property_id: PropertyIDSchema.nullish(),
    property_type: PropertyTypeSchema,
    name: z.string(),
    identifiers: z.tuple([z.object({
            type: PropertyIdentifierTypesSchema,
            value: z.string()
        })]).rest(z.object({
        type: PropertyIdentifierTypesSchema,
        value: z.string()
    })),
    tags: z.array(PropertyTagSchema).nullish(),
    publisher_domain: z.string().nullish()
});

export const CreateMediaBuySuccessSchema = z.object({
    media_buy_id: z.string(),
    buyer_ref: z.string(),
    creative_deadline: z.string().nullish(),
    packages: z.array(PackageSchema),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const UpdateMediaBuyResponseSchema = z.union([UpdateMediaBuySuccessSchema, UpdateMediaBuyErrorSchema]);

export const GetProductsResponseSchema = z.object({
    products: z.array(ProductSchema),
    errors: z.array(ErrorSchema).nullish(),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const ProductFiltersSchema = z.object({
    delivery_type: DeliveryTypeSchema.nullish(),
    is_fixed_price: z.boolean().nullish(),
    format_types: z.array(FormatCategorySchema).nullish(),
    format_ids: z.array(FormatIDSchema).nullish(),
    standard_formats_only: z.boolean().nullish(),
    min_exposures: z.number().nullish(),
    start_date: z.string().nullish(),
    end_date: z.string().nullish(),
    budget_range: z.record(z.string(), z.unknown()).nullish(),
    countries: z.array(z.string()).nullish(),
    channels: z.array(AdvertisingChannelsSchema).nullish()
});

export const ListCreativeFormatsRequestSchema = z.object({
    format_ids: z.array(FormatIDSchema).nullish(),
    type: FormatCategorySchema.nullish(),
    asset_types: z.array(AssetContentTypeSchema).nullish(),
    max_width: z.number().nullish(),
    max_height: z.number().nullish(),
    min_width: z.number().nullish(),
    min_height: z.number().nullish(),
    is_responsive: z.boolean().nullish(),
    name_search: z.string().nullish(),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const FormatSchema = z.object({
    format_id: FormatIDSchema,
    name: z.string(),
    description: z.string().nullish(),
    preview_image: z.string().nullish(),
    example_url: z.string().nullish(),
    type: FormatCategorySchema,
    accepts_parameters: z.array(FormatIDParameterSchema).nullish(),
    renders: z.tuple([z.union([z.record(z.string(), z.unknown()), z.object({
                parameters_from_format_id: z.literal(true)
            })])]).rest(z.union([z.record(z.string(), z.unknown()), z.object({
            parameters_from_format_id: z.literal(true)
        })])).nullish(),
    assets_required: z.array(z.union([z.object({
            item_type: z.literal("individual"),
            asset_id: z.string(),
            asset_type: AssetContentTypeSchema,
            asset_role: z.string().nullish(),
            required: z.boolean().nullish(),
            requirements: z.record(z.string(), z.unknown()).nullish()
        }), z.object({
            item_type: z.literal("repeatable_group"),
            asset_group_id: z.string(),
            min_count: z.number(),
            max_count: z.number(),
            assets: z.array(z.object({
                asset_id: z.string(),
                asset_type: AssetContentType1Schema,
                asset_role: z.string().nullish(),
                required: z.boolean().nullish(),
                requirements: z.record(z.string(), z.unknown()).nullish()
            }))
        })])).nullish(),
    delivery: z.record(z.string(), z.unknown()).nullish(),
    supported_macros: z.array(z.string()).nullish(),
    output_format_ids: z.array(FormatID1Schema).nullish(),
    format_card: z.object({
        format_id: FormatID2Schema,
        manifest: z.record(z.string(), z.unknown())
    }).nullish(),
    format_card_detailed: z.object({
        format_id: FormatID3Schema,
        manifest: z.record(z.string(), z.unknown())
    }).nullish()
});

export const PackageRequestSchema = z.object({
    buyer_ref: z.string(),
    product_id: z.string(),
    format_ids: z.tuple([FormatIDSchema]).rest(FormatIDSchema).nullish(),
    budget: z.number(),
    pacing: PacingSchema.nullish(),
    pricing_option_id: z.string(),
    bid_price: z.number().nullish(),
    targeting_overlay: TargetingOverlaySchema.nullish(),
    creative_ids: z.array(z.string()).nullish(),
    creatives: z.array(CreativeAssetSchema).nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const CreateMediaBuyResponseSchema = z.union([CreateMediaBuySuccessSchema, CreateMediaBuyErrorSchema]);

export const SyncCreativesRequestSchema = z.object({
    creatives: z.array(CreativeAssetSchema),
    creative_ids: z.array(z.string()).nullish(),
    assignments: z.record(z.string(), z.array(z.string())).nullish(),
    delete_missing: z.boolean().nullish(),
    dry_run: z.boolean().nullish(),
    validation_mode: ValidationModeSchema.nullish(),
    push_notification_config: PushNotificationConfigSchema.nullish(),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const CreativeFiltersSchema = z.object({
    format: z.string().nullish(),
    formats: z.array(z.string()).nullish(),
    status: CreativeStatusSchema.nullish(),
    statuses: z.array(CreativeStatus1Schema).nullish(),
    tags: z.array(z.string()).nullish(),
    tags_any: z.array(z.string()).nullish(),
    name_contains: z.string().nullish(),
    creative_ids: z.array(z.string()).nullish(),
    created_after: z.string().nullish(),
    created_before: z.string().nullish(),
    updated_after: z.string().nullish(),
    updated_before: z.string().nullish(),
    assigned_to_package: z.string().nullish(),
    assigned_to_packages: z.array(z.string()).nullish(),
    media_buy_ids: z.array(z.string()).nullish(),
    buyer_refs: z.array(z.string()).nullish(),
    unassigned: z.boolean().nullish(),
    has_performance_data: z.boolean().nullish()
});

export const UpdateMediaBuyRequestSchema = UpdateMediaBuyRequest1Schema;

export const GetMediaBuyDeliveryResponseSchema = z.object({
    notification_type: z.union([z.literal("scheduled"), z.literal("final"), z.literal("delayed"), z.literal("adjusted")]).nullish(),
    partial_data: z.boolean().nullish(),
    unavailable_count: z.number().nullish(),
    sequence_number: z.number().nullish(),
    next_expected_at: z.string().nullish(),
    reporting_period: z.object({
        start: z.string(),
        end: z.string()
    }),
    currency: z.string(),
    aggregated_totals: z.object({
        impressions: z.number(),
        spend: z.number(),
        clicks: z.number().nullish(),
        video_completions: z.number().nullish(),
        media_buy_count: z.number()
    }).nullish(),
    media_buy_deliveries: z.array(z.object({
        media_buy_id: z.string(),
        buyer_ref: z.string().nullish(),
        status: z.union([z.literal("pending"), z.literal("active"), z.literal("paused"), z.literal("completed"), z.literal("failed"), z.literal("reporting_delayed")]),
        expected_availability: z.string().nullish(),
        is_adjusted: z.boolean().nullish(),
        pricing_model: PricingModelSchema.nullish(),
        totals: DeliveryMetricsSchema.and(z.object({
            effective_rate: z.number().nullish()
        })),
        by_package: z.array(DeliveryMetricsSchema.and(z.object({
            package_id: z.string(),
            buyer_ref: z.string().nullish(),
            pacing_index: z.number().nullish(),
            pricing_model: PricingModel1Schema,
            rate: z.number(),
            currency: z.string(),
            delivery_status: z.union([z.literal("delivering"), z.literal("completed"), z.literal("budget_exhausted"), z.literal("flight_ended"), z.literal("goal_met")]).nullish(),
            paused: z.boolean().nullish()
        }))),
        daily_breakdown: z.array(z.object({
            date: z.string(),
            impressions: z.number(),
            spend: z.number()
        })).nullish()
    })),
    errors: z.array(ErrorSchema).nullish(),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const ListAuthorizedPropertiesResponseSchema = z.object({
    publisher_domains: z.tuple([z.string()]).rest(z.string()),
    primary_channels: z.tuple([AdvertisingChannelsSchema]).rest(AdvertisingChannelsSchema).nullish(),
    primary_countries: z.tuple([z.string()]).rest(z.string()).nullish(),
    portfolio_description: z.string().nullish(),
    advertising_policies: z.string().nullish(),
    last_updated: z.string().nullish(),
    errors: z.array(ErrorSchema).nullish(),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const ProvidePerformanceFeedbackRequestSchema = ProvidePerformanceFeedbackRequest1Schema;

export const ProvidePerformanceFeedbackResponseSchema = z.union([ProvidePerformanceFeedbackSuccessSchema, ProvidePerformanceFeedbackErrorSchema]);

export const WebhookAssetSchema = z.object({
    url: z.string(),
    method: HTTPMethodSchema.nullish(),
    timeout_ms: z.number().nullish(),
    supported_macros: z.array(z.string()).nullish(),
    required_macros: z.array(z.string()).nullish(),
    response_type: WebhookResponseTypeSchema,
    security: z.object({
        method: WebhookSecurityMethodSchema,
        hmac_header: z.string().nullish(),
        api_key_header: z.string().nullish()
    })
});

export const CreativeManifestSchema = z.object({
    format_id: FormatIDSchema,
    promoted_offering: z.string().nullish(),
    assets: z.record(z.string(), z.union([ImageAssetSchema, VideoAssetSchema, AudioAssetSchema, VASTAssetSchema, TextAssetSchema, URLAssetSchema, HTMLAssetSchema, JavaScriptAssetSchema, WebhookAssetSchema, CSSAssetSchema, DAASTAssetSchema, PromotedOfferingsSchema])),
    ext: ExtensionObjectSchema.nullish()
});

export const CreativeManifest1Schema = z.object({
    format_id: FormatID1Schema,
    promoted_offering: z.string().nullish(),
    assets: z.record(z.string(), z.union([ImageAssetSchema, VideoAssetSchema, AudioAssetSchema, VASTAssetSchema, TextAssetSchema, URLAssetSchema, HTMLAssetSchema, JavaScriptAssetSchema, WebhookAssetSchema, CSSAssetSchema, DAASTAssetSchema, PromotedOfferingsSchema])),
    ext: ExtensionObjectSchema.nullish()
});

export const SignalFiltersSchema = z.object({
    catalog_types: z.array(SignalCatalogTypeSchema).nullish(),
    data_providers: z.array(z.string()).nullish(),
    max_cpm: z.number().nullish(),
    min_coverage_percentage: z.number().nullish()
});

export const GetSignalsResponseSchema = z.object({
    signals: z.array(z.object({
        signal_agent_segment_id: z.string(),
        name: z.string(),
        description: z.string(),
        signal_type: SignalCatalogTypeSchema,
        data_provider: z.string(),
        coverage_percentage: z.number(),
        deployments: z.array(DeploymentSchema),
        pricing: z.object({
            cpm: z.number(),
            currency: z.string()
        })
    })),
    errors: z.array(ErrorSchema).nullish(),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const ActivateSignalResponseSchema = z.union([ActivateSignalSuccessSchema, ActivateSignalErrorSchema]);

export const GetProductsRequestSchema = z.object({
    brief: z.string().nullish(),
    brand_manifest: BrandManifestReferenceSchema.nullish(),
    filters: ProductFiltersSchema.nullish(),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const ListCreativeFormatsResponseSchema = z.object({
    formats: z.array(FormatSchema),
    creative_agents: z.array(z.object({
        agent_url: z.string(),
        agent_name: z.string().nullish(),
        capabilities: z.array(CreativeAgentCapabilitySchema).nullish()
    })).nullish(),
    errors: z.array(ErrorSchema).nullish(),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const CreateMediaBuyRequestSchema = z.object({
    buyer_ref: z.string(),
    packages: z.array(PackageRequestSchema),
    brand_manifest: BrandManifestReference1Schema,
    po_number: z.string().nullish(),
    start_time: StartTimingSchema,
    end_time: z.string(),
    reporting_webhook: PushNotificationConfigSchema.and(z.object({
        reporting_frequency: z.union([z.literal("hourly"), z.literal("daily"), z.literal("monthly")]),
        requested_metrics: z.array(z.union([z.literal("impressions"), z.literal("spend"), z.literal("clicks"), z.literal("ctr"), z.literal("video_completions"), z.literal("completion_rate"), z.literal("conversions"), z.literal("viewability"), z.literal("engagement_rate")])).nullish()
    })).nullish(),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const ListCreativesRequestSchema = z.object({
    filters: CreativeFiltersSchema.nullish(),
    sort: z.object({
        field: CreativeSortFieldSchema.nullish(),
        direction: SortDirectionSchema.nullish()
    }).nullish(),
    pagination: z.object({
        limit: z.number().nullish(),
        offset: z.number().nullish()
    }).nullish(),
    include_assignments: z.boolean().nullish(),
    include_performance: z.boolean().nullish(),
    include_sub_assets: z.boolean().nullish(),
    fields: z.array(z.union([z.literal("creative_id"), z.literal("name"), z.literal("format"), z.literal("status"), z.literal("created_date"), z.literal("updated_date"), z.literal("tags"), z.literal("assignments"), z.literal("performance"), z.literal("sub_assets")])).nullish(),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const BuildCreativeRequestSchema = z.object({
    message: z.string().nullish(),
    creative_manifest: CreativeManifestSchema.nullish(),
    target_format_id: FormatID1Schema,
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const BuildCreativeSuccessSchema = z.object({
    creative_manifest: CreativeManifestSchema,
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const PreviewCreativeRequestSchema = z.union([z.object({
        request_type: z.literal("single"),
        format_id: FormatIDSchema,
        creative_manifest: CreativeManifestSchema,
        inputs: z.array(z.object({
            name: z.string(),
            macros: z.record(z.string(), z.string()).nullish(),
            context_description: z.string().nullish()
        })).nullish(),
        template_id: z.string().nullish(),
        output_format: PreviewOutputFormatSchema.nullish(),
        context: ContextObjectSchema.nullish(),
        ext: ExtensionObjectSchema.nullish()
    }), z.object({
        request_type: z.literal("batch"),
        requests: z.tuple([z.object({
                format_id: FormatID2Schema,
                creative_manifest: CreativeManifest1Schema,
                inputs: z.array(z.object({
                    name: z.string(),
                    macros: z.record(z.string(), z.string()).nullish(),
                    context_description: z.string().nullish()
                })).nullish(),
                template_id: z.string().nullish(),
                output_format: PreviewOutputFormat1Schema.nullish()
            })]).rest(z.object({
            format_id: FormatID2Schema,
            creative_manifest: CreativeManifest1Schema,
            inputs: z.array(z.object({
                name: z.string(),
                macros: z.record(z.string(), z.string()).nullish(),
                context_description: z.string().nullish()
            })).nullish(),
            template_id: z.string().nullish(),
            output_format: PreviewOutputFormat1Schema.nullish()
        })),
        output_format: PreviewOutputFormat2Schema.nullish(),
        context: ContextObjectSchema.nullish(),
        ext: ExtensionObjectSchema.nullish()
    })]);

export const GetSignalsRequestSchema = z.object({
    signal_spec: z.string(),
    deliver_to: z.object({
        deployments: z.tuple([DestinationSchema]).rest(DestinationSchema),
        countries: z.array(z.string())
    }),
    filters: SignalFiltersSchema.nullish(),
    max_results: z.number().nullish(),
    context: ContextObjectSchema.nullish(),
    ext: ExtensionObjectSchema.nullish()
});

export const BuildCreativeResponseSchema = z.union([BuildCreativeSuccessSchema, BuildCreativeErrorSchema]);
