// Generated Zod v4 schemas from TypeScript types
// Generated at: 2025-11-21T14:53:01.659Z
// Sources:
//   - core.generated.ts (core types)
//   - tools.generated.ts (tool types)
//
// These schemas provide runtime validation for AdCP data structures
// Generated using ts-to-zod from TypeScript type definitions

// Generated by ts-to-zod
import { z } from "zod";

export const MediaBuyStatusSchema = z.union([z.literal("pending_activation"), z.literal("active"), z.literal("paused"), z.literal("completed")]);

export const PacingSchema = z.union([z.literal("even"), z.literal("asap"), z.literal("front_loaded")]);

export const PackageStatusSchema = z.union([z.literal("draft"), z.literal("active"), z.literal("paused"), z.literal("completed")]);

export const CreativeAssignmentSchema = z.object({
    creative_id: z.string(),
    weight: z.number().optional(),
    placement_ids: z.tuple([z.string()]).rest(z.string()).optional()
});

export const FormatIDSchema = z.object({
    agent_url: z.string(),
    id: z.string()
});

export const FrequencyCapSchema = z.object({
    suppress_minutes: z.number()
});

export const VASTVersionSchema = z.union([z.literal("2.0"), z.literal("3.0"), z.literal("4.0"), z.literal("4.1"), z.literal("4.2")]);

export const VASTTrackingEventSchema = z.union([z.literal("start"), z.literal("firstQuartile"), z.literal("midpoint"), z.literal("thirdQuartile"), z.literal("complete"), z.literal("impression"), z.literal("click"), z.literal("pause"), z.literal("resume"), z.literal("skip"), z.literal("mute"), z.literal("unmute"), z.literal("fullscreen"), z.literal("exitFullscreen"), z.literal("playerExpand"), z.literal("playerCollapse")]);

export const VASTVersion1Schema = z.union([z.literal("2.0"), z.literal("3.0"), z.literal("4.0"), z.literal("4.1"), z.literal("4.2")]);

export const DAASTVersionSchema = z.union([z.literal("1.0"), z.literal("1.1")]);

export const DAASTTrackingEventSchema = z.union([z.literal("start"), z.literal("firstQuartile"), z.literal("midpoint"), z.literal("thirdQuartile"), z.literal("complete"), z.literal("impression"), z.literal("pause"), z.literal("resume"), z.literal("skip"), z.literal("mute"), z.literal("unmute")]);

export const DAASTVersion1Schema = z.union([z.literal("1.0"), z.literal("1.1")]);

export const ImageAssetSchema = z.object({
    url: z.string(),
    width: z.number().optional(),
    height: z.number().optional(),
    format: z.string().optional(),
    alt_text: z.string().optional()
});

export const VideoAssetSchema = z.object({
    url: z.string(),
    width: z.number().optional(),
    height: z.number().optional(),
    duration_ms: z.number().optional(),
    format: z.string().optional(),
    bitrate_kbps: z.number().optional()
});

export const AudioAssetSchema = z.object({
    url: z.string(),
    duration_ms: z.number().optional(),
    format: z.string().optional(),
    bitrate_kbps: z.number().optional()
});

export const TextAssetSchema = z.object({
    content: z.string(),
    language: z.string().optional()
});

export const HTMLAssetSchema = z.object({
    content: z.string(),
    version: z.string().optional()
});

export const CSSAssetSchema = z.object({
    content: z.string(),
    media: z.string().optional()
});

export const VASTAssetSchema = z.union([z.object({
        delivery_type: z.literal("url"),
        url: z.string(),
        vast_version: VASTVersionSchema.optional(),
        vpaid_enabled: z.boolean().optional(),
        duration_ms: z.number().optional(),
        tracking_events: z.array(VASTTrackingEventSchema).optional()
    }), z.object({
        delivery_type: z.literal("inline"),
        content: z.string(),
        vast_version: VASTVersion1Schema.optional(),
        vpaid_enabled: z.boolean().optional(),
        duration_ms: z.number().optional(),
        tracking_events: z.array(VASTTrackingEventSchema).optional()
    })]);

export const DAASTAssetSchema = z.union([z.object({
        delivery_type: z.literal("url"),
        url: z.string(),
        daast_version: DAASTVersionSchema.optional(),
        duration_ms: z.number().optional(),
        tracking_events: z.array(DAASTTrackingEventSchema).optional(),
        companion_ads: z.boolean().optional()
    }), z.object({
        delivery_type: z.literal("inline"),
        content: z.string(),
        daast_version: DAASTVersion1Schema.optional(),
        duration_ms: z.number().optional(),
        tracking_events: z.array(DAASTTrackingEventSchema).optional(),
        companion_ads: z.boolean().optional()
    })]);

export const JavaScriptModuleTypeSchema = z.union([z.literal("esm"), z.literal("commonjs"), z.literal("script")]);

export const PromotedProductsSchema = z.object({
    manifest_skus: z.array(z.string()).optional(),
    manifest_tags: z.array(z.string()).optional(),
    manifest_category: z.string().optional(),
    manifest_query: z.string().optional()
});

export const AssetContentTypeSchema = z.union([z.literal("image"), z.literal("video"), z.literal("audio"), z.literal("text"), z.literal("markdown"), z.literal("html"), z.literal("css"), z.literal("javascript"), z.literal("vast"), z.literal("daast"), z.literal("promoted_offerings"), z.literal("url"), z.literal("webhook")]);

export const URLAssetTypeSchema = z.union([z.literal("clickthrough"), z.literal("tracker_pixel"), z.literal("tracker_script")]);

export const DeliveryTypeSchema = z.union([z.literal("guaranteed"), z.literal("non_guaranteed")]);

export const CPMFixedRatePricingOptionSchema = z.object({
    pricing_option_id: z.string(),
    pricing_model: z.literal("cpm"),
    rate: z.number(),
    currency: z.string(),
    is_fixed: z.literal(true),
    min_spend_per_package: z.number().optional()
});

export const CPMAuctionPricingOptionSchema = z.object({
    pricing_option_id: z.string(),
    pricing_model: z.literal("cpm"),
    currency: z.string(),
    is_fixed: z.literal(false),
    price_guidance: z.object({
        floor: z.number(),
        p25: z.number().optional(),
        p50: z.number().optional(),
        p75: z.number().optional(),
        p90: z.number().optional()
    }),
    min_spend_per_package: z.number().optional()
});

export const VCPMFixedRatePricingOptionSchema = z.object({
    pricing_option_id: z.string(),
    pricing_model: z.literal("vcpm"),
    rate: z.number(),
    currency: z.string(),
    is_fixed: z.literal(true),
    min_spend_per_package: z.number().optional()
});

export const VCPMAuctionPricingOptionSchema = z.object({
    pricing_option_id: z.string(),
    pricing_model: z.literal("vcpm"),
    currency: z.string(),
    is_fixed: z.literal(false),
    price_guidance: z.object({
        floor: z.number(),
        p25: z.number().optional(),
        p50: z.number().optional(),
        p75: z.number().optional(),
        p90: z.number().optional()
    }),
    min_spend_per_package: z.number().optional()
});

export const CPCPricingOptionSchema = z.object({
    pricing_option_id: z.string(),
    pricing_model: z.literal("cpc"),
    rate: z.number(),
    currency: z.string(),
    is_fixed: z.literal(true),
    min_spend_per_package: z.number().optional()
});

export const CPCVPricingOptionSchema = z.object({
    pricing_option_id: z.string(),
    pricing_model: z.literal("cpcv"),
    rate: z.number(),
    currency: z.string(),
    is_fixed: z.literal(true),
    min_spend_per_package: z.number().optional()
});

export const CPVPricingOptionSchema = z.object({
    pricing_option_id: z.string(),
    pricing_model: z.literal("cpv"),
    rate: z.number(),
    currency: z.string(),
    is_fixed: z.literal(true),
    parameters: z.object({
        view_threshold: z.union([z.number(), z.object({
                duration_seconds: z.number()
            })])
    }),
    min_spend_per_package: z.number().optional()
});

export const CPPPricingOptionSchema = z.object({
    pricing_option_id: z.string(),
    pricing_model: z.literal("cpp"),
    rate: z.number(),
    currency: z.string(),
    is_fixed: z.literal(true),
    parameters: z.object({
        demographic: z.string(),
        min_points: z.number().optional()
    }),
    min_spend_per_package: z.number().optional()
});

export const FlatRatePricingOptionSchema = z.object({
    pricing_option_id: z.string(),
    pricing_model: z.literal("flat_rate"),
    rate: z.number(),
    currency: z.string(),
    is_fixed: z.literal(true),
    parameters: z.object({
        duration_hours: z.number().optional(),
        sov_percentage: z.number().optional(),
        loop_duration_seconds: z.number().optional(),
        min_plays_per_hour: z.number().optional(),
        venue_package: z.string().optional(),
        estimated_impressions: z.number().optional(),
        daypart: z.string().optional()
    }).optional(),
    min_spend_per_package: z.number().optional()
});

export const PublisherPropertySelectorSchema = z.union([z.object({
        publisher_domain: z.string(),
        selection_type: z.literal("all")
    }), z.object({
        publisher_domain: z.string(),
        selection_type: z.literal("by_id"),
        property_ids: z.tuple([z.string()]).rest(z.string())
    }), z.object({
        publisher_domain: z.string(),
        selection_type: z.literal("by_tag"),
        property_tags: z.tuple([z.string()]).rest(z.string())
    })]);

export const PlacementSchema = z.object({
    placement_id: z.string(),
    name: z.string(),
    description: z.string().optional(),
    format_ids: z.tuple([FormatIDSchema]).rest(FormatIDSchema).optional()
});

export const PricingOptionSchema = z.union([CPMFixedRatePricingOptionSchema, CPMAuctionPricingOptionSchema, VCPMFixedRatePricingOptionSchema, VCPMAuctionPricingOptionSchema, CPCPricingOptionSchema, CPCVPricingOptionSchema, CPVPricingOptionSchema, CPPPricingOptionSchema, FlatRatePricingOptionSchema]);

export const MeasurementSchema = z.object({
    type: z.string(),
    attribution: z.string(),
    window: z.string().optional(),
    reporting: z.string()
});

export const FormatID1Schema = z.object({
    agent_url: z.string(),
    id: z.string()
});

export const FormatID2Schema = z.object({
    agent_url: z.string(),
    id: z.string()
});

export const ReportingFrequencySchema = z.union([z.literal("hourly"), z.literal("daily"), z.literal("monthly")]);

export const AvailableMetricSchema = z.union([z.literal("impressions"), z.literal("spend"), z.literal("clicks"), z.literal("ctr"), z.literal("video_completions"), z.literal("completion_rate"), z.literal("conversions"), z.literal("viewability"), z.literal("engagement_rate")]);

export const TargetingOverlaySchema = z.object({
    geo_country_any_of: z.array(z.string()).optional(),
    geo_region_any_of: z.array(z.string()).optional(),
    geo_metro_any_of: z.array(z.string()).optional(),
    geo_postal_code_any_of: z.array(z.string()).optional(),
    axe_include_segment: z.string().optional(),
    axe_exclude_segment: z.string().optional(),
    frequency_cap: FrequencyCapSchema.optional()
});

export const PackageSchema = z.object({
    package_id: z.string(),
    buyer_ref: z.string().optional(),
    product_id: z.string().optional(),
    budget: z.number().optional(),
    pacing: PacingSchema.optional(),
    pricing_option_id: z.string().optional(),
    bid_price: z.number().optional(),
    impressions: z.number().optional(),
    targeting_overlay: TargetingOverlaySchema.optional(),
    creative_assignments: z.array(CreativeAssignmentSchema).optional(),
    format_ids_to_provide: z.array(FormatIDSchema).optional(),
    status: PackageStatusSchema
});

export const BrandManifestSchema = z.object({
    url: z.string().optional(),
    name: z.string(),
    logos: z.array(z.object({
        url: z.string(),
        tags: z.array(z.string()).optional(),
        width: z.number().optional(),
        height: z.number().optional()
    })).optional(),
    colors: z.object({
        primary: z.string().optional(),
        secondary: z.string().optional(),
        accent: z.string().optional(),
        background: z.string().optional(),
        text: z.string().optional()
    }).optional(),
    fonts: z.object({
        primary: z.string().optional(),
        secondary: z.string().optional(),
        font_urls: z.array(z.string()).optional()
    }).optional(),
    tone: z.string().optional(),
    tagline: z.string().optional(),
    assets: z.array(z.object({
        asset_id: z.string(),
        asset_type: AssetContentTypeSchema,
        url: z.string(),
        tags: z.array(z.string()).optional(),
        name: z.string().optional(),
        description: z.string().optional(),
        width: z.number().optional(),
        height: z.number().optional(),
        duration_seconds: z.number().optional(),
        file_size_bytes: z.number().optional(),
        format: z.string().optional(),
        metadata: z.record(z.string(), z.unknown()).optional()
    })).optional(),
    product_catalog: z.object({
        feed_url: z.string(),
        feed_format: z.union([z.literal("google_merchant_center"), z.literal("facebook_catalog"), z.literal("custom")]).optional(),
        categories: z.array(z.string()).optional(),
        last_updated: z.string().optional(),
        update_frequency: z.union([z.literal("realtime"), z.literal("hourly"), z.literal("daily"), z.literal("weekly")]).optional()
    }).optional(),
    disclaimers: z.array(z.object({
        text: z.string(),
        context: z.string().optional(),
        required: z.boolean().optional()
    })).optional(),
    industry: z.string().optional(),
    target_audience: z.string().optional(),
    contact: z.object({
        email: z.string().optional(),
        phone: z.string().optional()
    }).optional(),
    metadata: z.object({
        created_date: z.string().optional(),
        updated_date: z.string().optional(),
        version: z.string().optional()
    }).optional()
});

export const JavaScriptAssetSchema = z.object({
    content: z.string(),
    module_type: JavaScriptModuleTypeSchema.optional()
});

export const URLAssetSchema = z.object({
    url: z.string(),
    url_type: URLAssetTypeSchema.optional(),
    description: z.string().optional()
});

export const BrandManifestReferenceSchema = z.union([BrandManifestSchema, z.string()]);

export const ReportingCapabilitiesSchema = z.object({
    available_reporting_frequencies: z.tuple([ReportingFrequencySchema]).rest(ReportingFrequencySchema),
    expected_delay_minutes: z.number(),
    timezone: z.string(),
    supports_webhooks: z.boolean(),
    available_metrics: z.array(AvailableMetricSchema)
});

export const MediaBuySchema = z.object({
    media_buy_id: z.string(),
    buyer_ref: z.string().optional(),
    status: MediaBuyStatusSchema,
    promoted_offering: z.string(),
    total_budget: z.number(),
    packages: z.array(PackageSchema),
    creative_deadline: z.string().optional(),
    created_at: z.string().optional(),
    updated_at: z.string().optional()
});

export const PromotedOfferingsSchema = z.object({
    brand_manifest: BrandManifestReferenceSchema,
    product_selectors: PromotedProductsSchema.optional(),
    offerings: z.array(z.object({
        name: z.string(),
        description: z.string().optional(),
        assets: z.array(z.record(z.string(), z.unknown())).optional()
    })).optional(),
    asset_selectors: z.object({
        tags: z.array(z.string()).optional(),
        asset_types: z.array(z.union([z.literal("image"), z.literal("video"), z.literal("audio"), z.literal("vast"), z.literal("daast"), z.literal("text"), z.literal("url"), z.literal("html"), z.literal("css"), z.literal("javascript"), z.literal("webhook")])).optional(),
        exclude_tags: z.array(z.string()).optional()
    }).optional()
});

export const CreativeAssetSchema = z.object({
    creative_id: z.string(),
    name: z.string(),
    format_id: FormatIDSchema,
    assets: z.record(z.string(), z.union([ImageAssetSchema, VideoAssetSchema, AudioAssetSchema, TextAssetSchema, HTMLAssetSchema, CSSAssetSchema, JavaScriptAssetSchema, VASTAssetSchema, DAASTAssetSchema, PromotedOfferingsSchema, URLAssetSchema])),
    inputs: z.array(z.object({
        name: z.string(),
        macros: z.record(z.string(), z.string()).optional(),
        context_description: z.string().optional()
    })).optional(),
    tags: z.array(z.string()).optional(),
    approved: z.boolean().optional()
});

// ====== TOOL SCHEMAS ======
// Generated by ts-to-zod
export const ErrorSchema = z.object({
    code: z.string(),
    message: z.string(),
    field: z.string().optional(),
    suggestion: z.string().optional(),
    retry_after: z.number().optional(),
    details: z.record(z.string(), z.unknown()).optional()
});

export const FormatCategorySchema = z.union([z.literal("audio"), z.literal("video"), z.literal("display"), z.literal("native"), z.literal("dooh"), z.literal("rich_media"), z.literal("universal")]);

export const CreativeAgentCapabilitySchema = z.union([z.literal("validation"), z.literal("assembly"), z.literal("generation"), z.literal("preview")]);

export const StartTimingSchema = z.union([z.literal("asap"), z.string()]);

export const ValidationModeSchema = z.union([z.literal("strict"), z.literal("lenient")]);

export const CreativeActionSchema = z.union([z.literal("created"), z.literal("updated"), z.literal("unchanged"), z.literal("failed"), z.literal("deleted")]);

export const CreativeSortFieldSchema = z.union([z.literal("created_date"), z.literal("updated_date"), z.literal("name"), z.literal("status"), z.literal("assignment_count"), z.literal("performance_score")]);

export const SortDirectionSchema = z.union([z.literal("asc"), z.literal("desc")]);

export const CreativeStatusSchema = z.union([z.literal("processing"), z.literal("approved"), z.literal("rejected"), z.literal("pending_review")]);

export const SubAssetSchema = z.union([z.object({
        asset_kind: z.literal("media"),
        asset_type: z.string(),
        asset_id: z.string(),
        content_uri: z.string()
    }), z.object({
        asset_kind: z.literal("text"),
        asset_type: z.string(),
        asset_id: z.string(),
        content: z.union([z.string(), z.array(z.string())])
    })]);

export const UpdateMediaBuyRequest2Schema = z.record(z.string(), z.unknown());

export const PricingModelSchema = z.union([z.literal("cpm"), z.literal("vcpm"), z.literal("cpc"), z.literal("cpcv"), z.literal("cpv"), z.literal("cpp"), z.literal("flat_rate")]);

export const DeliveryMetricsSchema = z.record(z.string(), z.unknown()).and(z.object({
    impressions: z.number().optional(),
    spend: z.number().optional(),
    clicks: z.number().optional(),
    ctr: z.number().optional(),
    views: z.number().optional(),
    completed_views: z.number().optional(),
    completion_rate: z.number().optional(),
    conversions: z.number().optional(),
    leads: z.number().optional(),
    grps: z.number().optional(),
    reach: z.number().optional(),
    frequency: z.number().optional(),
    quartile_data: z.object({
        q1_views: z.number().optional(),
        q2_views: z.number().optional(),
        q3_views: z.number().optional(),
        q4_views: z.number().optional()
    }).optional(),
    dooh_metrics: z.object({
        loop_plays: z.number().optional(),
        screens_used: z.number().optional(),
        screen_time_seconds: z.number().optional(),
        sov_achieved: z.number().optional(),
        calculation_notes: z.string().optional(),
        venue_breakdown: z.array(z.object({
            venue_id: z.string(),
            venue_name: z.string().optional(),
            venue_type: z.string().optional(),
            impressions: z.number(),
            loop_plays: z.number().optional(),
            screens_used: z.number().optional()
        })).optional()
    }).optional()
}));

export const PricingModel1Schema = z.union([z.literal("cpm"), z.literal("vcpm"), z.literal("cpc"), z.literal("cpcv"), z.literal("cpv"), z.literal("cpp"), z.literal("flat_rate")]);

export const ListAuthorizedPropertiesRequestSchema = z.object({
    publisher_domains: z.tuple([z.string()]).rest(z.string()).optional(),
    context: z.object({}).optional()
});

export const AdvertisingChannelsSchema = z.union([z.literal("display"), z.literal("video"), z.literal("audio"), z.literal("native"), z.literal("dooh"), z.literal("ctv"), z.literal("podcast"), z.literal("retail"), z.literal("social")]);

export const ProvidePerformanceFeedbackRequest2Schema = z.record(z.string(), z.unknown());

export const ProvidePerformanceFeedbackResponseSchema = z.union([z.object({
        success: z.literal(true),
        context: z.object({}).optional()
    }), z.object({
        errors: z.tuple([ErrorSchema]).rest(ErrorSchema),
        context: z.object({}).optional()
    })]);

export const PreviewOutputFormatSchema = z.union([z.literal("url"), z.literal("html")]);

export const PreviewOutputFormat1Schema = z.union([z.literal("url"), z.literal("html")]);

export const PreviewOutputFormat2Schema = z.union([z.literal("url"), z.literal("html")]);

export const PreviewRenderSchema = z.union([z.object({
        render_id: z.string(),
        output_format: z.literal("url"),
        preview_url: z.string(),
        role: z.string(),
        dimensions: z.object({
            width: z.number(),
            height: z.number()
        }).optional(),
        embedding: z.object({
            recommended_sandbox: z.string().optional(),
            requires_https: z.boolean().optional(),
            supports_fullscreen: z.boolean().optional(),
            csp_policy: z.string().optional()
        }).optional()
    }), z.object({
        render_id: z.string(),
        output_format: z.literal("html"),
        preview_html: z.string(),
        role: z.string(),
        dimensions: z.object({
            width: z.number(),
            height: z.number()
        }).optional(),
        embedding: z.object({
            recommended_sandbox: z.string().optional(),
            requires_https: z.boolean().optional(),
            supports_fullscreen: z.boolean().optional(),
            csp_policy: z.string().optional()
        }).optional()
    }), z.object({
        render_id: z.string(),
        output_format: z.literal("both"),
        preview_url: z.string(),
        preview_html: z.string(),
        role: z.string(),
        dimensions: z.object({
            width: z.number(),
            height: z.number()
        }).optional(),
        embedding: z.object({
            recommended_sandbox: z.string().optional(),
            requires_https: z.boolean().optional(),
            supports_fullscreen: z.boolean().optional(),
            csp_policy: z.string().optional()
        }).optional()
    })]);

export const DestinationSchema = z.union([z.object({
        type: z.literal("platform"),
        platform: z.string(),
        account: z.string().optional()
    }), z.object({
        type: z.literal("agent"),
        agent_url: z.string(),
        account: z.string().optional()
    })]);

export const SignalCatalogTypeSchema = z.union([z.literal("marketplace"), z.literal("custom"), z.literal("owned")]);

export const ActivateSignalRequestSchema = z.object({
    signal_agent_segment_id: z.string(),
    deployments: z.tuple([DestinationSchema]).rest(DestinationSchema),
    context: z.object({}).optional()
});

export const ListCreativeFormatsRequestSchema = z.object({
    format_ids: z.array(FormatIDSchema).optional(),
    type: FormatCategorySchema.optional(),
    asset_types: z.array(AssetContentTypeSchema).optional(),
    max_width: z.number().optional(),
    max_height: z.number().optional(),
    min_width: z.number().optional(),
    min_height: z.number().optional(),
    is_responsive: z.boolean().optional(),
    name_search: z.string().optional(),
    context: z.object({}).optional()
});

export const SyncCreativesResponseSchema = z.union([z.object({
        dry_run: z.boolean().optional(),
        creatives: z.array(z.object({
            creative_id: z.string(),
            action: CreativeActionSchema,
            platform_id: z.string().optional(),
            changes: z.array(z.string()).optional(),
            errors: z.array(z.string()).optional(),
            warnings: z.array(z.string()).optional(),
            preview_url: z.string().optional(),
            expires_at: z.string().optional(),
            assigned_to: z.array(z.string()).optional(),
            assignment_errors: z.record(z.string(), z.string()).optional()
        })),
        context: z.object({}).optional()
    }), z.object({
        errors: z.tuple([ErrorSchema]).rest(ErrorSchema),
        context: z.object({}).optional()
    })]);

export const GetMediaBuyDeliveryRequestSchema = z.object({
    media_buy_ids: z.array(z.string()).optional(),
    buyer_refs: z.array(z.string()).optional(),
    status_filter: z.union([MediaBuyStatusSchema, z.array(MediaBuyStatusSchema)]).optional(),
    start_date: z.string().optional(),
    end_date: z.string().optional(),
    context: z.object({}).optional()
});

export const GetMediaBuyDeliveryResponseSchema = z.object({
    notification_type: z.union([z.literal("scheduled"), z.literal("final"), z.literal("delayed"), z.literal("adjusted")]).optional(),
    partial_data: z.boolean().optional(),
    unavailable_count: z.number().optional(),
    sequence_number: z.number().optional(),
    next_expected_at: z.string().optional(),
    reporting_period: z.object({
        start: z.string(),
        end: z.string()
    }),
    currency: z.string(),
    aggregated_totals: z.object({
        impressions: z.number(),
        spend: z.number(),
        clicks: z.number().optional(),
        video_completions: z.number().optional(),
        media_buy_count: z.number()
    }).optional(),
    media_buy_deliveries: z.array(z.object({
        media_buy_id: z.string(),
        buyer_ref: z.string().optional(),
        status: z.union([z.literal("pending"), z.literal("active"), z.literal("paused"), z.literal("completed"), z.literal("failed"), z.literal("reporting_delayed")]),
        expected_availability: z.string().optional(),
        is_adjusted: z.boolean().optional(),
        pricing_model: PricingModelSchema.optional(),
        totals: DeliveryMetricsSchema.and(z.object({
            effective_rate: z.number().optional()
        })),
        by_package: z.array(DeliveryMetricsSchema.and(z.object({
            package_id: z.string(),
            buyer_ref: z.string().optional(),
            pacing_index: z.number().optional(),
            pricing_model: PricingModel1Schema,
            rate: z.number(),
            currency: z.string()
        }))),
        daily_breakdown: z.array(z.object({
            date: z.string(),
            impressions: z.number(),
            spend: z.number()
        })).optional()
    })),
    errors: z.array(ErrorSchema).optional(),
    context: z.object({}).optional()
});

export const ListAuthorizedPropertiesResponseSchema = z.object({
    publisher_domains: z.tuple([z.string()]).rest(z.string()),
    primary_channels: z.tuple([AdvertisingChannelsSchema]).rest(AdvertisingChannelsSchema).optional(),
    primary_countries: z.tuple([z.string()]).rest(z.string()).optional(),
    portfolio_description: z.string().optional(),
    advertising_policies: z.string().optional(),
    last_updated: z.string().optional(),
    errors: z.array(ErrorSchema).optional(),
    context: z.object({}).optional()
});

export const PreviewCreativeResponseSchema = z.union([z.object({
        response_type: z.literal("single"),
        previews: z.tuple([z.object({
                preview_id: z.string(),
                renders: z.tuple([PreviewRenderSchema]).rest(PreviewRenderSchema),
                input: z.object({
                    name: z.string(),
                    macros: z.record(z.string(), z.string()).optional(),
                    context_description: z.string().optional()
                })
            })]).rest(z.object({
            preview_id: z.string(),
            renders: z.tuple([PreviewRenderSchema]).rest(PreviewRenderSchema),
            input: z.object({
                name: z.string(),
                macros: z.record(z.string(), z.string()).optional(),
                context_description: z.string().optional()
            })
        })),
        interactive_url: z.string().optional(),
        expires_at: z.string(),
        context: z.object({}).optional()
    }), z.object({
        response_type: z.literal("batch"),
        results: z.tuple([z.union([z.object({
                    success: z.literal(true).optional()
                }), z.object({
                    success: z.literal(false).optional()
                })])]).rest(z.union([z.object({
                success: z.literal(true).optional()
            }), z.object({
                success: z.literal(false).optional()
            })])),
        context: z.object({}).optional()
    })]);

export const SignalFiltersSchema = z.object({
    catalog_types: z.array(SignalCatalogTypeSchema).optional(),
    data_providers: z.array(z.string()).optional(),
    max_cpm: z.number().optional(),
    min_coverage_percentage: z.number().optional()
});

export const GetSignalsRequestSchema = z.object({
    signal_spec: z.string(),
    deliver_to: z.object({
        deployments: z.tuple([DestinationSchema]).rest(DestinationSchema),
        countries: z.array(z.string())
    }),
    filters: SignalFiltersSchema.optional(),
    max_results: z.number().optional(),
    context: z.object({}).optional()
});
