name: Lint Commit Messages

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install commitlint
        run: |
          npm install --save-dev @commitlint/config-conventional @commitlint/cli || \
          (echo "Retry 1 failed, waiting 30s..." && sleep 30 && npm install --save-dev @commitlint/config-conventional @commitlint/cli) || \
          (echo "Retry 2 failed, waiting 60s..." && sleep 60 && npm install --save-dev @commitlint/config-conventional @commitlint/cli)

      - name: Validate PR title follows conventional commits
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "$PR_TITLE" | npx commitlint --config commitlint.config.js

      - name: Validate all commits in PR
        run: |
          npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
