name: Release Please

on:
  push:
    branches:
      - main
    # Only trigger when library code or package files change
    # Skip when only server/testing UI changes
    paths-ignore:
      - 'src/public/**'
      - 'src/server/**'
      - 'test/**'
      - '**.test.js'
      - '**.test.ts'
      - 'docs/**'
      - 'fly.toml'
      - '.nvmrc'
      - '.vscode/**'
      - '.idea/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # Configuration is in release-please-config.json
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      # Publish to NPM when a release is created
      - name: Checkout code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Setup Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: npm ci

      - name: Publish to NPM
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create package summary
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "## 📦 Package Published Successfully" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Package:** @adcp/client" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}" >> $GITHUB_STEP_SUMMARY
          echo "**Tag:** ${{ steps.release.outputs.tag_name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Registry:** https://npmjs.com/package/@adcp/client" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Installation" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo "npm install @adcp/client" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
